version: '3'

services:
  harmonify:
    image: postgres:15
    container_name: harmonify-local
    hostname: harmonify
    restart: always
    ports:
      - 5438:5432
    volumes:
      - ./.db:/var/lib/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmonify